baseURL = 'https://zhou-efr.github.io'
languageCode = 'en-us'
description = "Le panda géant (Ailuropoda melanoleuca) est une espèce de mammifères, habituellement classée dans la famille des ursidés (Ursidae), endémique de la Chine centrale."
images = ['/files/image/panda-default.jpg']
title = 'Grosser Panda.JPG'

[markup.goldmark.renderer]
    unsafe= true

[menu]
    [[menu.main]]
      identifier = "Home"
      name = 'Home'
      page = 'Home'
      url = '/'
      weight = 1
    [[menu.main]]
      identifier = "Resume"
      name = 'Resume'
      page = 'Resume'
      url = '/resume'
      weight = 2
    [[menu.main]]
      identifier = "Cyber-log"
      name = 'Cyber-log'
      page = 'Cyber-log'
      url = '/cyber-log'
      weight = 3
    [[menu.main]]
      identifier = 'About'
      name = 'About'
      page = 'About'
      url = '/about'
      weight = 4


[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'layouts'
  target = 'layouts'
[[module.mounts]]
  source = 'data'
  target = 'data'
[[module.mounts]]
  source = 'i18n'
  target = 'i18n'
[[module.mounts]]
  source = 'archetypes'
  target = 'archetypes'
